theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: "assets/docs"
    values:
      sitemap: false

nav_links:
  - title: Home
    url: /
  - title: Featured Project
    url: /featured
  - title: Other Projects
    url: /projects
  - title: CV
    url: /cv

logo: assets/images/profile1_small.png
title: Thabani Biyela, ACA
description: A curated collection of my work in finance automation showcasing how I use Python, SQL, JavaScript, and GCP to solve complex financial problems and build data-driven tools.

# These settings control the types of collections used by the template
