theme: jekyll-theme-minimal

nav_links:
  - title: Home
    url: /
  - title: CV
    url: /cv
title: Home
logo: data/images/profile1_small.png
description: A curated collection of my work.
# These settings control the types of collections used by the template
collections:
  cv:
    output: true
    permalink: /:collection/:path/


# These settings control how pages and collections are included in the site
defaults:
  # _cv
  - scope:
      path: ""
      type: cv
    values:
      layout: default
