theme: jekyll-theme-minimal
logo: data/images/profile1.png
title: Thabani's homepage
description: A curated collection of my work in finance automation showcasing how I use Python, SQL, JavaScript, and GCP to solve complex financial problems and build data-driven tools. Bookmark this to keep an eye on my project updates!
